### ISSUE TITLE
convert to a Go module

### ISSUE THREAD

**Issue by mvdan** [google/go-write#4]
Pretty please :) No need to start tagging releases of course, but I don't think there's a need to avoid Go modules.

**Comment by stapelberg** [comment]
I considered this before publishing, but given that I don’t want to tag releases currently, what’s the upside of having this package be a Go module currently? Will that enable any new features/workflows?

**Comment by mvdan** [comment]
Given the temporary lack of releases, and that you have no external dependencies, it really doesn't make a big difference for modules depending on you.

I'd personally still do it, for consistency, and to enable others to work on it without requiring GOPATH.
